export const urgencyOptions = ['Hot', 'Now', 'When Able']
export const urgencyValues = [10, 3, 1]
export const customerValueOptions = ['Epic Gold', 'Epic High', 'Epic Medium', 'Epic Low', 'Story Gold', 'Story High', 'Story Medium', 'Story Low', 'Zero'];
export const customerValueValues = [75, 25, 15, 5, 15, 5, 3, 1, 0];
export const customersAffectedOptions = ['All', 'Most', 'Many', 'Some', 'Rare', 'None'];
export const customersAffectedValues = [1, 0.8, 0.6, 0.4, 0.2, 0];
export const developerValueOptions = ['Epic Gold', 'Epic High', 'Epic Medium', 'Epic Low', 'Story Gold', 'Story High', 'Story Medium', 'Story Low', 'Zero'];
export const developerValueValues = [75, 25, 15, 5, 15, 5, 3, 1, 0];
export const developersAffectedOptions = ['All', 'Most', 'Many', 'Some', 'Rare', 'None'];
export const developersAffectedValues = [1, 0.8, 0.6, 0.4, 0.2, 0];
export const developerEffortOptions = ['Team Large', 'Team Medium', 'Team Small', 'Dev Very Large', 'Dev Large', 'Dev Medium', 'Dev Small', 'Dev Tiny'];
export const developerEffortValues = [15, 10, 5, 2, 1, 0.5, 0.3, 0.1];
export const flaggedChar = '*';
export const notFlaggedChar = ' ';
export const priorityScoreStartingString = '[';
export const priorityScoreEndingString = ']';
export const priorityValuesStartingString = '\nPriority Values: [';
export const priorityValuesEndingString = ']';